# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
development:
  api_key: 68e0325141a343219ee5d9fdb6e1ad75
  secret_key: b78c26d0665fdd45a184c41af0897b60
  canvas_page_name: jordanrtest
  callback_url: http://db240296.fb.joyent.us:3070/
  tunnel:
    public_host_username:
    public_host: 
    public_port: 4007
    local_port: 3070

test:
  api_key:
  secret_key:
  canvas_page_name:
  callback_url:
  tunnel:
    public_host_username: 
    public_host: 
    public_port:
    local_port:

production:
  api_key: 
  secret_key:
  canvas_page_name: couplerater
  callback_url: http://db240296.fb.joyent.us:3000/ 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
